# Redirect www to non-www
[[redirects]]
  from = "https://www.getlegaldocs.co.uk/*"
  to = "https://getlegaldocs.co.uk/:splat"
  status = 301
  force = true

# Gumroad version
[[redirects]]
  from = "/gumroad"
  to = "/gumroad.html"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "."
  functions = "netlify/functions"
